server:
  port: @user.server.port@

spring:
  profiles:
    active: @env@
  kafka:
    producer:
      bootstrap-servers: @kafka.bootstraps@


  datasource:
    url: @db.url@
    username: @db.username@
    password: @db.password@
    type: com.alibaba.druid.pool.DruidDataSource
topic:
  log: @topic.log@
mybatis:
#  config-location: com.ycit.user.mapper
  type-aliases-package: com.ycit.user.bean
  mapper-locations: classpath:mapper/*.xml


